version: "3.3"
services:
  app:
    tty: true
    stdin_open: true
    build: .
    command: puma -C config/puma.rb
    volumes:
      - .:/app
      - /Users/seocahill/code/dts_explorer:/app/lib/dts_explorer
      - ixbrl:/ixbrl
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
      - validator
      - arelle
  
  validator:
    build: /Users/seocahill/code/xbrl_validator
    ports:
      - "4567:4567"
    volumes: 
      - /Users/seocahill/code/xbrl_validator:/app

  arelle:
    image: seocahill/arelle:latest
    ports:
      - "8080:8080"
    volumes: 
      - ixbrl:/ixbrl

  db:
    image: postgres:alpine
    volumes:
      - postgres:/var/lib/postgresql/data
    configs:
      - source: postgresql.conf
        target: /var/lib/postgresql/data/postgresql.conf

  # pghero:
  #   image: ankane/pghero
  #   environment:
  #     - DATABASE_URL=postgres://postgres@db:5432/circle_dev
  #   ports:
  #     - "8090:8080"

  redis:
    image: redis:alpine

volumes:
  postgres:
  ixbrl:

# configs:
#   postgresql.conf:
#     file: ./config/postgresql.conf